# datasource
mariadb-url: jdbc:mariadb://localhost:3306/sansam_db?characterEncoding=UTF-8&serverTimezone=UTC
mariadb-username: ssafy
mariadb-password: ssafy!234

# oauth2
kakao-client-id: bf26dca29ba9a83f993a702eb0e2bab5
kakao-client-secret: vNEC5800OpeiElowImDDUSYbpYv3HSN4