# datasource
mariadb-url: jdbc:mariadb://172.17.0.1:3306/sansam_db?characterEncoding=UTF-8&serverTimezone=UTC
mariadb-username: ssafy
mariadb-password: ssafy!234

# oauth2
kakao-client-id: bf26dca29ba9a83f993a702eb0e2bab5
kakao-client-secret: vNEC5800OpeiElowImDDUSYbpYv3HSN4
kakao-redirect-uri: "https://j8d205.p.ssafy.io/api/login/oauth2/code/kakao"
kakao-success-login-uri: "https://j8d205.p.ssafy.io/login?"
kakao-success-signup-uri: "https://j8d205.p.ssafy.io/signup/1?no="
kakao-failure-login-uri: "https://j8d205.p.ssafy.io/api/oauth2/authorization/kakao"

#kakao-redirect-uri: "http://localhost:5000/login/oauth2/code/kakao"
#kakao-success-login-uri: "http://localhost:3000/login?"
#kakao-success-signup-uri: "http://localhost:3000/signup/1?no="
#kakao-failure-login-uri: "http://localhost:5000/oauth2/authorization/kakao"

# jwt
secret-keyword: "https://lab.ssafy.com/s08-bigdata-recom-sub2/S08P22D205-sansam-2bsagioads-abasdbfasdc"
access-expiration: 1800000  # timeMilliSeconds
refresh-expiration: 14  # days