spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/sansam_db?characterEncoding=UTF-8&&serverTimezone=UTC
    username: ssafy
    password: ssafy!234

server:
  port: 5000