# datasource
mariadb-url: jdbc:mariadb://localhost:3306/sansam_db?characterEncoding=UTF-8&serverTimezone=UTC
mariadb-username: ssafy
mariadb-password: ssafy!234

# oauth2
kakao-client-id: bf26dca29ba9a83f993a702eb0e2bab5
kakao-client-secret: vNEC5800OpeiElowImDDUSYbpYv3HSN4
kakao-redirect-uri: "https://j8d205.p.ssafy.io/api/login/oauth2/code/kakao"
#kakao-redirect-uri: "http://localhost:5000/login/oauth2/code/kakao"

# jwt
secret-keyword: "https://lab.ssafy.com/s08-bigdata-recom-sub2/S08P22D205-sansam-2bsagioads-abasdbfasdc"
access-expiration: 1800000  # timeMilliSeconds
refresh-expiration: 14  # days